"""Tests for the section-aware Discord markdown chunker."""
from __future__ import annotations

from ironclad.notifications.discord import _fence_tables, _md_chunks


SAMPLE_REPORT = """# IRONCLAD MATCHUP REPORT
## CLE @ CIN
### Week 18

---

## GAME FORECAST

| | CLE | CIN |
|---|---|---|
| **Win Probability** | 23.7% | 76.3% |
| **Projected Score** | 21 | 29 |

---

## GAME ENVIRONMENT

- **Stadium:** Paycor
- **Weather:** 34°F

---

## TEAM PROJECTIONS

| Stat | CLE | CIN |
|---|---|---|
| Total Yards | 469 | 452 |
| Pass Yards | 349 | 321 |

---

*Generated by ironclad-v2*
"""


def test_fence_tables_wraps_pipe_block():
    """A block of `|`-prefixed lines gets triple-backtick fences added around it."""
    text = "## HEADER\n\n| A | B |\n|---|---|\n| 1 | 2 |\n\nfooter"
    out = _fence_tables(text)
    assert "```" in out
    assert out.count("```") == 2
    assert "| A | B |" in out
    assert "footer" in out


def test_fence_tables_closes_at_eof():
    """Fence closes even if the file ends inside a table."""
    text = "| A | B |\n| 1 | 2 |"
    out = _fence_tables(text)
    assert out.count("```") == 2
    assert out.endswith("```")


def test_md_chunks_all_within_limit():
    """No chunk exceeds the 1900-char limit."""
    chunks = _md_chunks(SAMPLE_REPORT)
    assert all(len(c) <= 1900 for c in chunks)
    assert len(chunks) >= 1


def test_md_chunks_never_splits_inside_table():
    """A chunk containing `|` table rows must contain a matching opening and closing fence."""
    chunks = _md_chunks(SAMPLE_REPORT)
    for chunk in chunks:
        assert chunk.count("```") % 2 == 0, f"Unbalanced fences: {chunk!r}"


def test_md_chunks_preserves_content():
    """All non-fence content is preserved."""
    chunks = _md_chunks(SAMPLE_REPORT)
    joined = "\n".join(chunks)
    for phrase in ["CLE @ CIN", "GAME FORECAST", "76.3%", "Total Yards",
                   "GAME ENVIRONMENT", "TEAM PROJECTIONS", "Paycor"]:
        assert phrase in joined


def test_md_chunks_forces_split_over_limit():
    """A report much larger than the limit is split into multiple chunks."""
    long_report = SAMPLE_REPORT * 20
    chunks = _md_chunks(long_report, limit=1000)
    assert len(chunks) > 1
    assert all(len(c) <= 1000 for c in chunks)
